title: Runze Meng's Homepage
page-top-title: Runze Meng
top-section-bg-text: Data Science and Big Data Technology
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Runze Meng 2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/Runze-Meng
sections:
  - id: home
    nav: HOME
    title: Runze Meng&ensp;|&ensp;孟润泽
    href: '#page-top' # Default to '#<id>' if not specified
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
